### ISSUE TITLE
how to convert official BAIR dataset

### ISSUE THREAD

**Issue by JunyaoHu** [XiYe20/VPTR#10]
Hello dear author, I want to know how to convert official BAIR dataset to your dataset format. Thanks!
```
/BAIR
     test/
         example_0/
            0000.png
            0001.png
```

**Comment by XiYe20** [comment]
Hi, please see: utils/read_BAIR_tfrecords.py

**Comment by JunyaoHu** [comment]
Thank you. It was an oversight of mine.
