### ISSUE TITLE
code for testing BAIR dataset

### ISSUE THREAD

**Issue by JunyaoHu** [XiYe20/VPTR#11]
I use your [Test_VPTR.ipynb](https://github.com/XiYe20/VPTR/blob/main/Test_VPTR.ipynb) to test on BAIR dataset, but I get a wrong output which is more and more gray.

ground truth

![image](https://user-images.githubusercontent.com/67564714/228612783-c9330cda-c799-4de9-a082-51195f788b6d.png)

result

![image](https://user-images.githubusercontent.com/67564714/228612864-b0e1119e-a578-40fa-9c84-81661b3dd1bf.png)

[Test_VPTR_BAIR_my.txt](https://github.com/XiYe20/VPTR/files/11103370/Test_VPTR_BAIR_my.txt)

**Comment by XiYe20** [comment]
Hi, did you set the decoder outlayer to be 'Tanh' for BAIR dataset?

**Comment by JunyaoHu** [comment]
it works thanks! i think you can update the comment here, i didnt notice your train file

![image](https://user-images.githubusercontent.com/67564714/228623676-46bff56f-6360-44da-94b6-c30964a215fc.png)

https://github.com/XiYe20/VPTR/blob/b876364ee19100dccde35ef402bcc2fb1930fdf1/train_FAR.py#L180

![image](https://user-images.githubusercontent.com/67564714/228623534-451c52af-779c-4366-afbb-67282fe3608e.png)
