### ISSUE TITLE
Can you post the instructions to do inference from custom frames too?

### ISSUE THREAD

**Issue by mayank64ce** [XiYe20/VPTR#12]

**Comment by shawnye1994** [comment]
Hi, you can use custom frames by replacing the "past_frames" in Test_VPTR.ipynb with your own custom frames. But please remember to resize and normalize your custom frames as what  utils/dataset.py does. Please see the "get_dataloader()" function for all transforms applied to the datasets.

**Comment by XiYe20** [comment]
Hi, you can use custom frames by replacing the "past_frames" in Test_VPTR.ipynb with your own custom frames. But please remember to resize and normalize your custom frames as what utils/dataset.py does. Please see the "get_dataloader()" function for all transforms applied to the datasets.
