### ISSUE TITLE
显卡

### ISSUE THREAD

**Issue by wenyufeng936** [XiYe20/VPTR#14]
![image](https://github.com/user-attachments/assets/b80089dc-b400-454d-8176-9e421b8907c6)
您好，论文中有提到使用的是3090，为何使用V100-32G的显卡运行显示显存不够，这篇论文实验是用3090跑的吗？

**Comment by XiYe20** [comment]
Hi, thank you very much for your interest in our work. Here we denote that the specific experiment for inference/training time measurement is conducted on a RTX3090 GPU with a small batch size. If you are trying to train the model, the auto encoder can be trained with a single RTX3090 within reasonable time. For the Transformer predictor, we recommend you to use the DDP training script, and set the batch size based on the number of GPUs/Memory you have. And four V100-32G GPUs would be good enough.
