### ISSUE TITLE
model parameters

### ISSUE THREAD

**Issue by Candy-moon** [XiYe20/VPTR#2]
Could you give me the total number of model parameters? Thanks~

**Comment by XiYe20** [comment]
Hi. Here are the number of parameters:

- Encoder num_parameters: 46772256
- Decoder num_parameters: 1589185
- Discriminator num_parameters: 2763585
- NAR Transformer num_parameters: 118368576
- FAR Transformer num_parameters: 88008096

The number of parameters are calculated by: 
**num_parameters = sum(p.numel() for p in model.parameters() if p.requires_grad)**

For training datasets with different color channels, e.g., 1(Grayscale) or 3 (RGB), the number of Encoder and Decoder parameters are slightly different (should be negligible). I have updated the code, you may try it by yourself.
