### ISSUE TITLE
Dataset np array key issue

### ISSUE THREAD

**Issue by May-226** [XiYe20/VPTR#4]
When running the notebook, the MovingMNISTDataset dataloader will be called, and the way to create dictionary 'data' is based on the key of the input .npz file, however, the original dataset downloaded from http://www.cs.toronto.edu/~nitish/unsupervised_video/ seems not to have the key 'clips'. Is it possible for you to share your splitted dataset somehow? Thx!

**Comment by XiYe20** [comment]
Hi, I use the movingmnist dataset provided by this paper: https://github.com/google/e3d_lstm. Sorry for the inconvenience.

**Comment by May-226** [comment]
Thanks for the prompt reply! It works now.
