### ISSUE TITLE
About applying your model to other datasets

### ISSUE THREAD

**Issue by summersnowfish** [XiYe20/VPTR#7]
Hi, thank you very much for your excellent work. Regarding video future frame prediction, I want to use it in the field of video anomaly detection. So I want to use your model to see if it can predict future frames in a video anomaly detection dataset scenario (such as the ShanghaiTech dataset). May I use the ShanghaiTech dataset to train your model? Is this solution feasible?

**Comment by XiYe20** [comment]
Hi, Thank you very much for your interest in our model. I am sorry that I cannot give you any suggestion about your research as I don't know anything about anomaly detection. For sure that you can train the model with any of your own dataset and adapt it for any of your own task.

**Comment by summersnowfish** [comment]
Thank you for such a quick reply. I will try it with anomaly detection dataset.
Thanks again for your work and reply. wish you a happy life.
