### ISSUE TITLE
MovingMNIST dataset

### ISSUE THREAD

**Issue by fnuabhimanyu** [XiYe20/VPTR#9]
Can you please post the link for the MovingMNIST dataset?

**Comment by XiYe20** [comment]
Hi, please check the link here: https://github.com/XiYe20/VPTR/issues/4

**Comment by fnuabhimanyu** [comment]
Thanks for the quick response. Also for the BAIR dataset, I guess you used this script https://github.com/edenton/svg/blob/master/data/convert_bair.py to extract the data? Wchich version of TF does it use?

**Comment by XiYe20** [comment]
Hi, I used Tensorflow 2.6.0, it should work.
